version: '3.8'

services:
  backend:
    build:
      context: ./money-tracker-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./money-tracker-backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/money_tracker
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./money-tracker-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./money-tracker-frontend:/app
      - /app/node_modules
    command: npm start

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: money_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
